### ISSUE TITLE
Antlr Downloadable Zip is Incomplete

### ISSUE THREAD

**Issue by cozy1** [antlr/antlrcs#48]
When I downloaded the antlrcs source using the GitHub zip file https://github.com/antlr/antlrcs/archive/master.zip  the 'Reference' fold is empty because it contains some illegal characters (may be OS dependent) https://github.com/antlr/antlrcs/tree/master/Reference

This prevents the zip source from building.  In order to actually build a copy of the repo I had to Fork it and then build it.  Some users may rely on building the downloadable zip.

**Comment by sharwell** [comment]
The items in the Reference folder are submodules, which means the contents are not included in this repository by design. You will either need to download them from the corresponding repositories (clicking the links will take to you them) and create the folder structure yourself, or clone the repository and update submodules in order to build.
